name: ExoPlaSim

services:
  exoplasim:
    container_name: ExoPlaSim
    user: "${UID:-1001}:${GID:-1001}"
    build:
      context: .
      args:
        UID: "${UID:-1001}"
        GID: "${GID:-1001}"
    volumes:
      - "${BUILD_DIR:-./build}:/build"
